'''
Generated by Airflow Datalake! Do not edit!
author: tuancamtbtx
Timestamp 2024-08-03T17:09:31.157517+07:00
'''

from airflow import DAG

from airfactory.dagrender import AirlakeDagFactory

config_filepath = "./conf/example_dag_factory.yaml"

factory= AirlakeDagFactory(config_filepath=config_filepath)
factory.cleans_dags()
factory.generate_dags(globals())

